
### protected route returns true/false according to the login status.
GET http://localhost:4000

### end point for getting auth0 access token
GET http://localhost:4000/auth

### end point for login/signUp Via Auth0. (open in browser)
GET http://localhost:4000/login

### end point for fetching user profile. (open in browser)
GET http://localhost:4000/profile

### end point for logout (open in browser)
GET http://localhost:4000/logout

### end point for fetching user profile, right after authentication. (open in browser)
GET http://localhost:4000/api/v1/insta/auth

### end point for fetcing instagram data of a user using username
GET http://localhost:4000/api/v1/insta/get-data/hivie.community